version: 2

sources:
  - name: trip
    meta:
      external_location: "/home/yoda/code/dataeng/project/yellow_trip/ingestion/data/*.parquet"
    tables:
      - name: yellow_trip
        meta:
          external_location: "/home/yoda/code/dataeng/project/yellow_trip/ingestion/data/*.parquet"
